### ISSUE TITLE
HRR_cut.R number of rows

### ISSUE THREAD

**Issue by cascoamarillo** [EA2106-Universite-Francois-Rabelais/Expression-network-analysis#2]
Hi,

I have some issues coming after getting the vectors (hrr) and calling HRR_cut.R for processing them. My doubt is with the options -s, -S and -c from  HRR_cut.R, if am I doing it right:
`-s INTEGER, --size=INTEGER
      	Number of rows in the processed matrix (not REAL size), see hrr standard output
      
      	-S INTEGER, --realsize=INTEGER
      		Number of rows in the matrix (REAL size), see hrr standard output
      
      	-c INTEGER, --subsize=INTEGER
      		Number of row in the submatrix, see hrr standard output`

I get some errors coming from it, like 
`NULL
Error: unexpected end of input
Execution halted`

So I am going to place here my data and see if someone can chime in. Thanks in advance:

My data file is and RNAseq reads count matrix; pretty simple: 18760 transcripts and 6 conditions
`$ head TagSeqExample.dat 
T1a	T1b	T2	T3	N1	N2
Gene_00001	0	0	2	0	0	1
Gene_00002	20	8	12	5	19	26
Gene_00003	3	0	2	0	0	0
Gene_00004	75	84	241	149	271	257
Gene_00005	10	16	4	0	4	10
Gene_00006	129	126	451	223	243	149
Gene_00007	13	4	21	19	31	4
Gene_00008	0	3	0	0	0	0
Gene_00009	202	122	256	43	287	357`

For hrr I used
`mpirun -np 4 ./hrr ../TagSeqExample.dat rankmatrix doubleprecision`

All good: four vector files.txt. Then created a folder, like PCC_lt, moved there the 4 .txt vector files. Before that, this is the output from hrr:

`mpirun -np 4 ./hrr ../TagSeqExample.dat rankmatrix doubleprecision
-- start --
-- start --
-- start --
-- start --
args (rankmatrix)
args (doubleprecision)
args (rankmatrix)
args (doubleprecision)
procs: [4]  rank: [1]  inputfile: [../TagSeqExample.dat]  localsave: [0]
args (rankmatrix)
args (doubleprecision)
procs: [4]  rank: [2]  inputfile: [../TagSeqExample.dat]  localsave: [0]
args (rankmatrix)
args (doubleprecision)
procs: [4]  rank: [3]  inputfile: [../TagSeqExample.dat]  localsave: [0]
procs: [4]  rank: [0]  inputfile: [../TagSeqExample.dat]  localsave: [0]
bench_file: gen_size: 18764  data_size: 6  real_gen_size: 18760 
RANK: 0: broadcasting data
RANK: 1: receiving dim: 18764 6:  allocated size: 450336
RANK: 1: broadcasting data
RANK: 2: receiving dim: 18764 6:  allocated size: 450336
RANK: 2: broadcasting data
RANK: 3: receiving dim: 18764 6:  allocated size: 450336
RANK: 3: broadcasting data
RANK: 0: receiving dim end: 18764 6
RANK: 1: receiving dim end: 18764 6
RANK: 2: receiving dim end: 18764 6
RANK: 3: receiving dim end: 18764 6
RANK: 0: build_rank_matrix start 4691 18764
RANK: 2: build_rank_matrix start 4691 18764
RANK: 1: build_rank_matrix start 4691 18764
RANK: 3: build_rank_matrix start 4691 18764
RANK: 1: build_rank_matrix end
RANK: 1: process_max_hrr: procs 4  gen_size: 18764  data_size: 6  gen_sub_size: 4691
RANK: 2: build_rank_matrix end
RANK: 2: process_max_hrr: procs 4  gen_size: 18764  data_size: 6  gen_sub_size: 4691
RANK: 0: build_rank_matrix end
RANK: 0: process_max_hrr: procs 4  gen_size: 18764  data_size: 6  gen_sub_size: 4691
RANK: 3: build_rank_matrix end
RANK: 3: process_max_hrr: procs 4  gen_size: 18764  data_size: 6  gen_sub_size: 4691
RANK: 2: process_max_hrr END
RANK: 2 save_all_result: 88021924 18764 4691
RANK: 0: process_max_hrr END
RANK: 0 save_all_result: 88021924 18764 4691
RANK: 0: save data to disk: start (0.txt) 
RANK: 1: process_max_hrr END
RANK: 1 save_all_result: 88021924 18764 4691
RANK: 3: process_max_hrr END
RANK: 3 save_all_result: 88021924 18764 4691
RANK: 0: save data to disk: end
RANK: 1: save data to disk: start (1.txt) 
RANK: 1: save data to disk: end
RANK: 2: save data to disk: start (2.txt) 
RANK: 2: save data to disk: end
RANK: 3: save data to disk: start (3.txt) 
RANK: 3: save data to disk: end
`
Now, for running HRR_cut.R into /PCC_lt folder, I started using
`HRR_cut.R -n 4 -a ../TagSeqExample.ids -s 18764 -S 18760 -c 4691 -r PCC -m 4`

According to hhr output; 
`bench_file: gen_size: 18764  data_size: 6  real_gen_size: 18760
...
RANK: 1: process_max_hrr: procs 4  gen_size: 18764  data_size: 6  gen_sub_size: 4691 `

I used:
gen_size: 18764, as -s "Number of rows in the processed matrix (not REAL size)"
real_gen_size: 18760, as -S "Number of rows in the matrix (REAL size)"
gen_sub_size: 4691, as -c "Number of row in the submatrix"

BUT, something is not right. I have tried to change this numbers to other potential candidates, but nothing works, Maybe I misinterpreted the documentation? Although, I get some output results:
`$ head Gene_00001
"lt" "corr"
"1" "Gene_00001" 0
"2" "Gene_00002" 8774
"3" "Gene_00003" 7775
"4" "Gene_00004" 5345
"5" "Gene_00005" 11558
"6" "Gene_00006" 4687
"7" "Gene_00007" 12862
"8" "Gene_00008" 12811
"9" "Gene_00009" 5828`
`$ tail Gene_00001
"18755" "Gene_18755" 5189
"18756" "Gene_18756" 8697
"18757" "Gene_18757" 6017
"18758" "Gene_18758" 7630
"18759" "Gene_18759" 11019
"18760" "Gene_18760" 9392
"18761" "Gene_18760" 9392
"18762" "Gene_18760" 9392
"18763" "Gene_18760" 9392
"18764" "Gene_18760" 9392
`

Btw, TagSeqExample.ids is just one column with ids, right?:
`$ head TagSeqExample.ids 
Gene_00001
Gene_00002
Gene_00003
Gene_00004
Gene_00005
Gene_00006
Gene_00007
Gene_00008
Gene_00009
Gene_00010
`

**Comment by EA2106-Universite-Francois-Rabelais** [comment]
Hi @cascoamarillo , thanks for your interest for this program. I have an updated version of the R script to collect the best coexpressed gene pairs. I will post it as soon as possible!

**Comment by cascoamarillo** [comment]
Thanks for the quick reply! Looking forward to it.

**Comment by EA2106-Universite-Francois-Rabelais** [comment]
I updated the code. It now works with a full bash script to calculate the HRR and extract the best pairs. Please do not hesitate to contact me if you have any problem with it. 
I also updated the hrr.tgz, I think you should download and recompile it.
Good luck!

**Comment by cascoamarillo** [comment]
Yes, it nicely works! Thank you. Now trying to understand how igraph works.
Closing.

**Comment by EA2106-Universite-Francois-Rabelais** [comment]
I will post some tips... 


De: "cascoamarillo" <notifications@github.com> 
À: "EA2106-Universite-Francois-Rabelais/Expression-network-analysis" <Expression-network-analysis@noreply.github.com> 
Cc: "Thomas Duge De Bernonville" <thomas.duge@univ-tours.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Vendredi 8 Janvier 2021 16:42:20 
Objet: Re: [EA2106-Universite-Francois-Rabelais/Expression-network-analysis] HRR_cut.R number of rows (#2) 





Yes, it nicely works! Thank you. Now trying to understand how igraph works. 
Closing.
