### ISSUE TITLE
There is something wrong when I make the "hrr"

### ISSUE THREAD

**Issue by zyx336** [EA2106-Universite-Francois-Rabelais/Expression-network-analysis#3]
to install the software, I typed 'make' in hrr directory, but it can't find the liblapack.a, 
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c array_d.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c array_f.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c array_i.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c array_list_d.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c array_list_f.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c bench_file.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c compute.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c compute_weighted_pcc.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c compute_weighted_pcc_d.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c display.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c dump.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c main.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c mem.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c mem_pool.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   -c svd.c
mpicc -Wall -DMAIN_MAIN_ -O2 -Ic:/Users/rod/Work/Applis/lapack-3.5.0/lapacke/include/   array_d.o array_f.o array_i.o array_list_d.o array_list_f.o bench_file.o compute.o compute_weighted_pcc.o compute_weighted_pcc_d.o display.o dump.o main.o mem.o mem_pool.o svd.o  c:/Users/rod/Work/Applis/lapack-3.5.0/liblapacke.a c:/Users/rod/Work/Applis/lapack-3.5.0/liblapack.a c:/Users/rod/Work/Applis/lapack-3.5.0/libtmglib.a  -o hrr -lm -lblas -lgfortran
**gcc: error: c:/Users/rod/Work/Applis/lapack-3.5.0/liblapacke.a: No such file or directory
gcc: error: c:/Users/rod/Work/Applis/lapack-3.5.0/liblapack.a: No such file or directory
gcc: error: c:/Users/rod/Work/Applis/lapack-3.5.0/libtmglib.a: No such file or directory**
make: *** [Makefile:26: hrr] Error 1
I am sure that I have install blas cblas and lapack. Do you have some ideas with this error?

**Comment by EA2106-Universite-Francois-Rabelais** [comment]
Hi @zyx336 ,
We apologize for this: the default paths are that from our local lib. Please provide the correct paths to the different lib*.a in the Makefile before typing 'make' in the console.
Good luck!

**Comment by zyx336** [comment]
I solved this problem with your method. The program is running normally. Thank you! @EA2106-Universite-Francois-Rabelais

**Comment by EA2106-Universite-Francois-Rabelais** [comment]
Glad to hear!
